GET http://localhost:3000/players/
###

POST http://localhost:3000/players/
Content-Type: application/json 

{
    "player_name": "Vishal",
  "jersey_number": 17,
  "role": "Bowler"
}

###
GET http://localhost:3000/players/8/
###

PUT http://localhost:3000/players/7/
Content-Type : application/json

{
    "player_name" : "SaiVulavapati",
    "jersey_number" : 54,
    "role" : "All-Rounder"
}
###

DELETE http://localhost:3000/players/1/